name: mvvm_utils
description: A collection of utils to support Flutter's recommended MVVM architecture
version: 0.2.0
repository: https://github.com/pierremrtn/mvvm_utils

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  async: ^2.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
