import 'dart:async';

import 'package:collection/collection.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:mvvm_utils/mvvm_utils.dart';

export 'command_state.dart';

typedef CommandAction0<R> = FutureOr<R> Function();
typedef CommandAction1<P, R> = FutureOr<R> Function(P);
typedef CommandSuccessCallback<R> = void Function(R value);
typedef CommandFailureCallback = void Function(Object error);

abstract class CommandRestrictionController extends Listenable {
  const CommandRestrictionController();
  bool get enabled;
}

class DependsOnCommands
    with ChangeNotifier
    implements CommandRestrictionController {
  DependsOnCommands(List<Command> commands)
      : _commands = commands,
        _allCommands = Listenable.merge(commands) {
    _allCommands.addListener(notifyListeners);
  }

  final Listenable _allCommands;
  final List<Command> _commands;

  @override
  bool get enabled => _commands.none((c) => c.state.isSucceeded == false);
}

class CommandRestrictionSelector<T extends Listenable>
    implements CommandRestrictionController {
  CommandRestrictionSelector(this.listenable, this.selector);

  final T listenable;
  final bool Function(T) selector;

  @override
  bool get enabled => selector(listenable);

  @override
  void addListener(VoidCallback listener) => listenable.addListener(listener);

  @override
  void removeListener(VoidCallback listener) =>
      listenable.removeListener(listener);
}

class Command<R> with ChangeNotifier {
  Command({
    CommandRestrictionController? restrictionController,
    this.onFailure,
    this.onSuccess,
  }) : _restrictionController = restrictionController {
    _restrictionController?.addListener(notifyListeners);
  }

  final CommandSuccessCallback<R>? onSuccess;
  final CommandFailureCallback? onFailure;
  final CommandRestrictionController? _restrictionController;

  CommandState<R> _state = CommandState.initial();
  CommandState<R> get state => _state;

  bool get enabled => _restrictionController?.enabled ?? true;
  bool get disabled => !enabled;

  /// Return the result of the last execute call
  /// Calling execute **does not** reset result value while the command is running
  /// This allows to keep displaying previous result (such as error message) until
  /// a new result is available.
  ///
  /// If you need the status of the currently running action, uses [status] instead
  FutureOr<Result<R>?> _execute(
    FutureOr<R> Function() action, {
    CommandSuccessCallback<R>? onSuccess,
    CommandFailureCallback? onError,
  }) async {
    if (state.isRunning || _restrictionController?.enabled == false) {
      return null;
    }

    _state = CommandState.running();
    notifyListeners();

    late final Result<R> executionResult;
    try {
      final res = await action();
      _state = CommandState.success(res);
      executionResult = Success(res);
    } catch (e) {
      _state = CommandState.failure(e);
      executionResult = Failure(e);
    } finally {
      state.whenOrNull(
        success: onSuccess,
        failure: onFailure,
      );
      notifyListeners();
    }
    return executionResult;
  }

  @override
  void dispose() {
    _restrictionController?.removeListener(notifyListeners);
    super.dispose();
  }
}

/// A [Command] that accepts no arguments.
class Command0<T> extends Command<T> {
  /// Creates a [Command0] with the provided [CommandAction0].
  Command0(
    this._action, {
    super.restrictionController,
    super.onFailure,
    super.onSuccess,
  });

  final CommandAction0<T> _action;

  FutureOr<Result<T>?> Function()? toNullableCallbackWithOptions({
    required bool nullWhenDisabled,
    required bool nullWhenRunning,
  }) =>
      (nullWhenDisabled && disabled) || (nullWhenRunning && state.isRunning)
          ? null
          : this.execute;

  FutureOr<Result<T>?> Function()? get toNullableCallback =>
      toNullableCallbackWithOptions(
        nullWhenDisabled: true,
        nullWhenRunning: true,
      );

  /// Executes the command's action.
  /// Returns the result generated by this action execution.
  /// If the command is already running, returns null.
  FutureOr<Result<T>?> execute() async {
    return await _execute(() => _action());
  }
}

class Command1<P, R> extends Command<R> {
  Command1(
    this._action, {
    super.restrictionController,
    super.onFailure,
    super.onSuccess,
  });

  final CommandAction1<P, R> _action;

  /// Executes the command's action.
  /// Returns the result generated by this action execution.
  /// If the command is already running, returns null.
  FutureOr<Result<R>?> execute(P param) async {
    return await _execute(() => _action(param));
  }
}
